insert into location (num_street, street, city, country) values ('6229', 'Aberg', 'Marseille', 'France');
insert into location (num_street, street, city, country) values ('3801', 'Sommers', 'Sumberrejo', 'Indonesia');
insert into location (num_street, street, city, country) values ('0', 'Basil', 'Ivanovskoye', 'Russia');
insert into location (num_street, street, city, country) values ('9', 'Stuart', 'Freiria', 'Portugal');
insert into location (num_street, street, city, country) values ('8', 'Pond', 'Shijiazhuang', 'China');
insert into location (num_street, street, city, country) values ('88336', 'Kipling', 'Orizari', 'Macedonia');
insert into location (num_street, street, city, country) values ('62540', 'Scofield', 'Yirga ‘Alem', 'Ethiopia');
insert into location (num_street, street, city, country) values ('0019', 'Daystar', 'Louisville', 'United States');
insert into location (num_street, street, city, country) values ('64', 'Mallory', 'Sangkalputung', 'Indonesia');
insert into location (num_street, street, city, country) values ('020', 'Prairieview', 'Penedono', 'Portugal');
insert into location (num_street, street, city, country) values ('094', 'Stoughton', 'San Ramón', 'Nicaragua');
insert into location (num_street, street, city, country) values ('432', 'Division', 'Libertad', 'Philippines');
insert into location (num_street, street, city, country) values ('435', 'Harper', 'Tengah', 'Indonesia');
insert into location (num_street, street, city, country) values ('862', 'Almo', 'Libice nad Cidlinou', 'Czech Republic');
insert into location (num_street, street, city, country) values ('9', 'Macpherson', 'München', 'Germany');
insert into location (num_street, street, city, country) values ('7733', 'Myrtle', 'Beiguoyuan', 'China');
insert into location (num_street, street, city, country) values ('76', 'Thompson', 'Łopuszno', 'Poland');
insert into location (num_street, street, city, country) values ('588', 'Lawn', 'Zakroczym', 'Poland');
insert into location (num_street, street, city, country) values ('189', 'Lillian', 'Botlhapatlou', 'Botswana');
insert into location (num_street, street, city, country) values ('34', 'Gina', 'Orléans', 'France');
insert into location (num_street, street, city, country) values ('2', 'Karstens', 'Le Puy-en-Velay', 'France');
insert into location (num_street, street, city, country) values ('062', 'Nancy', 'Jiamiao', 'China');
insert into location (num_street, street, city, country) values ('534', 'Bunker Hill', 'Gaoqiao', 'China');
insert into location (num_street, street, city, country) values ('23', 'Heffernan', 'Loppi', 'Finland');
insert into location (num_street, street, city, country) values ('5', 'Caliangt', 'Juancheng', 'China');
insert into location (num_street, street, city, country) values ('3', 'Blaine', 'Valerik', 'Russia');
insert into location (num_street, street, city, country) values ('64079', 'Mandrake', 'Devesa', 'Portugal');
insert into location (num_street, street, city, country) values ('098', 'Dunning', 'Chiriguaná', 'Colombia');
insert into location (num_street, street, city, country) values ('87', 'Killdeer', 'Nam Sách', 'Vietnam');
insert into location (num_street, street, city, country) values ('6', 'Michigan', 'Mastung', 'Pakistan');
insert into location (num_street, street, city, country) values ('9', 'Fairfield', 'Hirado', 'Japan');
insert into location (num_street, street, city, country) values ('035', 'Mallory', 'Brétigny-sur-Orge', 'France');
insert into location (num_street, street, city, country) values ('1958', 'Manitowish', 'Milano', 'Italy');
insert into location (num_street, street, city, country) values ('63404', 'Heffernan', 'Gromadka', 'Poland');
insert into location (num_street, street, city, country) values ('77603', 'Golf', 'Mikulášovice', 'Czech Republic');
insert into location (num_street, street, city, country) values ('8', 'Mifflin', 'Phú Lộc', 'Vietnam');
insert into location (num_street, street, city, country) values ('1', 'Pawling', 'Made', 'Indonesia');
insert into location (num_street, street, city, country) values ('10', 'Schlimgen', 'Little Baguio', 'Philippines');
insert into location (num_street, street, city, country) values ('9694', 'Glacier Hill', 'Uppsala', 'Sweden');
insert into location (num_street, street, city, country) values ('9010', 'Macpherson', 'Quwa', 'China');
insert into location (num_street, street, city, country) values ('4', 'Fieldstone', 'Chum Phae', 'Thailand');
insert into location (num_street, street, city, country) values ('1369', 'Ramsey', 'Błonie', 'Poland');
insert into location (num_street, street, city, country) values ('07732', 'Melvin', 'Kościerzyna', 'Poland');
insert into location (num_street, street, city, country) values ('30185', 'Brentwood', 'Hluboká nad Vltavou', 'Czech Republic');
insert into location (num_street, street, city, country) values ('17', 'Schiller', 'Tambakrejo', 'Indonesia');
insert into location (num_street, street, city, country) values ('566', 'Ronald Regan', 'Monguno', 'Nigeria');
insert into location (num_street, street, city, country) values ('38776', 'Gale', 'Anchang', 'China');
insert into location (num_street, street, city, country) values ('6886', 'Vidon', 'Lisia Góra', 'Poland');
insert into location (num_street, street, city, country) values ('6', 'Debs', 'Porciúncula', 'Brazil');
insert into location (num_street, street, city, country) values ('525', 'Summit', 'Stalbe', 'Latvia');
